#!/bin/sh -eu

for m in -m32 -mx32; do
	tests=tests$m
	rm -rf $tests
	mkdir $tests
	sed "s/^AM_CFLAGS[[:space:]]*=.*/& $m/" \
		tests/Makefile.am > $tests/Makefile.am
	for f in tests/*; do
		case "${f##*/}" in
		Makefile*) continue;;
		esac
		ln -s ../"$f" $tests/
	done
done

./xlat/gen.sh
./generate_mpers_am.sh

exec autoreconf -f -i "$@"
