#!/bin/sh -e

exec > mpers.am

echo "# Generated by $0; do not edit."
printf 'mpers_source_files = '

sed -n '/^strace_SOURCES[[:space:]]*=/,/^[[:space:]]*# end of strace_SOURCES/ s/^[[:space:]]*\([[:alnum:]][^.]*\.c\)[[:space:]]*\\$/\1/p' Makefile.am |
	xargs -r grep -lx '#[[:space:]]*include[[:space:]]\+MPERS_DEFS' |
	tr '\n' ' '
echo
