#!/bin/sh -e

id="$(git rev-parse --verify "${1:-@}^{commit}")"

j=-j`getconf _NPROCESSORS_ONLN 2> /dev/null` || j=

distdir=strace-dist-$$
abs_distdir="`pwd`/$distdir"
trap 'chmod -Rf u+w $abs_distdir; rm -rf $abs_distdir' 1 2 15 0

set -x
git clone -q -n -s .git "$distdir"

cd $distdir
git checkout -f "$id"

./git-set-file-times

./bootstrap

./configure --enable-maintainer-mode

make -s $j distcheck

if git describe --exact-match --match='v*' >/dev/null; then
	make -s $j news-check
else
	echo 'SKIP: make news-check'
fi

./make-dsc strace-*.tar.gz > ../strace.dsc

cat strace.spec > ../strace.spec

mv -f strace-*.tar.[gx]z ..
