#include "tests.h"

#if defined(HAVE_DRM_H) || defined(HAVE_DRM_DRM_H)

# include <errno.h>
# include <inttypes.h>
# include <stdio.h>
# include <stdlib.h>
# include <string.h>
# include <sys/ioctl.h>

# ifdef HAVE_DRM_H
#  include <drm.h>
# else
#  include <drm/drm.h>
# endif

# define TEST_NULL_ARG_EX(cmd, str)					\
	do {								\
		ioctl(-1, cmd, 0);					\
		printf("ioctl(-1, %s, NULL) = -1 EBADF (%m)\n", str);	\
	} while(0)

# define TEST_NULL_ARG(cmd) TEST_NULL_ARG_EX(cmd, #cmd)

static const unsigned long lmagic = (unsigned long) 0xdeadbeefbadc0dedULL;

int
main(void)
{
	TEST_NULL_ARG(DRM_IOCTL_VERSION);
	TEST_NULL_ARG(DRM_IOCTL_GET_UNIQUE);
	TEST_NULL_ARG(DRM_IOCTL_GET_MAGIC);
	TEST_NULL_ARG(DRM_IOCTL_IRQ_BUSID);
	TEST_NULL_ARG(DRM_IOCTL_GET_MAP);
	TEST_NULL_ARG(DRM_IOCTL_GET_CLIENT);
	TEST_NULL_ARG(DRM_IOCTL_SET_VERSION);
	TEST_NULL_ARG(DRM_IOCTL_MODESET_CTL);
	TEST_NULL_ARG(DRM_IOCTL_GEM_CLOSE);
	TEST_NULL_ARG(DRM_IOCTL_GEM_FLINK);
	TEST_NULL_ARG(DRM_IOCTL_GEM_OPEN);
	TEST_NULL_ARG(DRM_IOCTL_GET_CAP);
	TEST_NULL_ARG(DRM_IOCTL_SET_CLIENT_CAP);
	TEST_NULL_ARG(DRM_IOCTL_AUTH_MAGIC);
	TEST_NULL_ARG(DRM_IOCTL_BLOCK);
	TEST_NULL_ARG(DRM_IOCTL_UNBLOCK);
	TEST_NULL_ARG(DRM_IOCTL_CONTROL);
	TEST_NULL_ARG(DRM_IOCTL_ADD_MAP);
	TEST_NULL_ARG(DRM_IOCTL_ADD_BUFS);
	TEST_NULL_ARG(DRM_IOCTL_MARK_BUFS);
	TEST_NULL_ARG(DRM_IOCTL_INFO_BUFS);
	TEST_NULL_ARG(DRM_IOCTL_MAP_BUFS);
	TEST_NULL_ARG(DRM_IOCTL_FREE_BUFS);
	TEST_NULL_ARG(DRM_IOCTL_RM_MAP);
	TEST_NULL_ARG(DRM_IOCTL_SET_SAREA_CTX);
	TEST_NULL_ARG(DRM_IOCTL_GET_SAREA_CTX);
	TEST_NULL_ARG(DRM_IOCTL_ADD_CTX);
	TEST_NULL_ARG(DRM_IOCTL_RM_CTX);
	TEST_NULL_ARG(DRM_IOCTL_MOD_CTX);
	TEST_NULL_ARG(DRM_IOCTL_GET_CTX);
	TEST_NULL_ARG(DRM_IOCTL_SWITCH_CTX);
	TEST_NULL_ARG(DRM_IOCTL_NEW_CTX);
	TEST_NULL_ARG(DRM_IOCTL_RES_CTX);
	TEST_NULL_ARG(DRM_IOCTL_ADD_DRAW);
	TEST_NULL_ARG(DRM_IOCTL_RM_DRAW);
	TEST_NULL_ARG(DRM_IOCTL_LOCK);
	TEST_NULL_ARG(DRM_IOCTL_UNLOCK);
	TEST_NULL_ARG(DRM_IOCTL_FINISH);
	TEST_NULL_ARG(DRM_IOCTL_PRIME_HANDLE_TO_FD);
	TEST_NULL_ARG(DRM_IOCTL_PRIME_FD_TO_HANDLE);
	TEST_NULL_ARG(DRM_IOCTL_AGP_ENABLE);
	TEST_NULL_ARG(DRM_IOCTL_AGP_INFO);
	TEST_NULL_ARG(DRM_IOCTL_AGP_ALLOC);
	TEST_NULL_ARG(DRM_IOCTL_AGP_FREE);
	TEST_NULL_ARG(DRM_IOCTL_AGP_BIND);
	TEST_NULL_ARG(DRM_IOCTL_AGP_UNBIND);
	TEST_NULL_ARG(DRM_IOCTL_SG_ALLOC);
	TEST_NULL_ARG(DRM_IOCTL_SG_FREE);
	TEST_NULL_ARG(DRM_IOCTL_WAIT_VBLANK);
# ifdef DRM_IOCTL_CRTC_GET_SEQUENCE
	TEST_NULL_ARG(DRM_IOCTL_CRTC_GET_SEQUENCE);
# endif
# ifdef DRM_IOCTL_CRTC_QUEUE_SEQUENCE
	TEST_NULL_ARG(DRM_IOCTL_CRTC_QUEUE_SEQUENCE);
# endif
	TEST_NULL_ARG(DRM_IOCTL_MODE_GETRESOURCES);
	TEST_NULL_ARG(DRM_IOCTL_MODE_GETCRTC);
	TEST_NULL_ARG(DRM_IOCTL_MODE_SETCRTC);
	TEST_NULL_ARG(DRM_IOCTL_MODE_CURSOR);
	TEST_NULL_ARG(DRM_IOCTL_MODE_GETGAMMA);
	TEST_NULL_ARG(DRM_IOCTL_MODE_SETGAMMA);
	TEST_NULL_ARG(DRM_IOCTL_MODE_GETENCODER);
	TEST_NULL_ARG(DRM_IOCTL_MODE_ATTACHMODE);
	TEST_NULL_ARG(DRM_IOCTL_MODE_DETACHMODE);
	TEST_NULL_ARG(DRM_IOCTL_MODE_GETPROPERTY);
	TEST_NULL_ARG(DRM_IOCTL_MODE_SETPROPERTY);
	TEST_NULL_ARG(DRM_IOCTL_MODE_GETPROPBLOB);
	TEST_NULL_ARG(DRM_IOCTL_MODE_GETFB);
	TEST_NULL_ARG(DRM_IOCTL_MODE_ADDFB);
	TEST_NULL_ARG(DRM_IOCTL_MODE_RMFB);
	TEST_NULL_ARG(DRM_IOCTL_MODE_PAGE_FLIP);
	TEST_NULL_ARG(DRM_IOCTL_MODE_DIRTYFB);
	TEST_NULL_ARG(DRM_IOCTL_MODE_CREATE_DUMB);
	TEST_NULL_ARG(DRM_IOCTL_MODE_MAP_DUMB);
	TEST_NULL_ARG(DRM_IOCTL_MODE_DESTROY_DUMB);
	TEST_NULL_ARG(DRM_IOCTL_MODE_GETPLANERESOURCES);
	TEST_NULL_ARG(DRM_IOCTL_MODE_GETPLANE);
	TEST_NULL_ARG(DRM_IOCTL_MODE_SETPLANE);
	TEST_NULL_ARG(DRM_IOCTL_MODE_OBJ_GETPROPERTIES);
	TEST_NULL_ARG(DRM_IOCTL_MODE_OBJ_SETPROPERTY);
	TEST_NULL_ARG(DRM_IOCTL_MODE_CURSOR2);
	TEST_NULL_ARG(DRM_IOCTL_MODE_ATOMIC);
	TEST_NULL_ARG(DRM_IOCTL_MODE_CREATEPROPBLOB);
	TEST_NULL_ARG(DRM_IOCTL_MODE_DESTROYPROPBLOB);
# ifdef DRM_IOCTL_SYNCOBJ_CREATE
	TEST_NULL_ARG(DRM_IOCTL_SYNCOBJ_CREATE);
# endif
# ifdef DRM_IOCTL_SYNCOBJ_DESTROY
	TEST_NULL_ARG(DRM_IOCTL_SYNCOBJ_DESTROY);
# endif
# ifdef DRM_IOCTL_SYNCOBJ_HANDLE_TO_FD
	TEST_NULL_ARG(DRM_IOCTL_SYNCOBJ_HANDLE_TO_FD);
# endif
# ifdef DRM_IOCTL_SYNCOBJ_FD_TO_HANDLE
	TEST_NULL_ARG(DRM_IOCTL_SYNCOBJ_FD_TO_HANDLE);
# endif
# ifdef DRM_IOCTL_SYNCOBJ_WAIT
	TEST_NULL_ARG(DRM_IOCTL_SYNCOBJ_WAIT);
# endif
# ifdef DRM_IOCTL_SYNCOBJ_RESET
	TEST_NULL_ARG(DRM_IOCTL_SYNCOBJ_RESET);
# endif
# ifdef DRM_IOCTL_MODE_CREATE_LEASE
	TEST_NULL_ARG(DRM_IOCTL_MODE_CREATE_LEASE);
# endif
# ifdef DRM_IOCTL_MODE_LIST_LESSEES
	TEST_NULL_ARG(DRM_IOCTL_MODE_LIST_LESSEES);
# endif
# ifdef DRM_IOCTL_MODE_GET_LEASE
	TEST_NULL_ARG(DRM_IOCTL_MODE_GET_LEASE);
# endif
# ifdef DRM_IOCTL_MODE_REVOKE_LEASE
	TEST_NULL_ARG(DRM_IOCTL_MODE_REVOKE_LEASE);
# endif
# ifdef DRM_IOCTL_SYNCOBJ_TIMELINE_WAIT
	TEST_NULL_ARG(DRM_IOCTL_SYNCOBJ_TIMELINE_WAIT);
# endif
# ifdef DRM_IOCTL_SYNCOBJ_QUERY
	TEST_NULL_ARG(DRM_IOCTL_SYNCOBJ_QUERY);
# endif
# ifdef DRM_IOCTL_SYNCOBJ_TRANSFER
	TEST_NULL_ARG(DRM_IOCTL_SYNCOBJ_TRANSFER);
# endif
# ifdef DRM_IOCTL_SYNCOBJ_QUERY
	TEST_NULL_ARG(DRM_IOCTL_SYNCOBJ_TIMELINE_SIGNAL);
# endif

	ioctl(-1, DRM_IOCTL_MODE_GETCONNECTOR, 0);
	printf("ioctl(-1, DRM_IOWR(%#lx, %#lx) /* DRM_IOCTL_MODE_GETCONNECTOR */, NULL) = -1 EBADF (%m)\n",
	       (long unsigned int) _IOC_NR(DRM_IOCTL_MODE_GETCONNECTOR),
	       (long unsigned int) _IOC_SIZE(DRM_IOCTL_MODE_GETCONNECTOR));

	ioctl(-1, DRM_IOCTL_MODE_ADDFB2, 0);
	printf("ioctl(-1, DRM_IOWR(%#lx, %#lx) /* DRM_IOCTL_MODE_ADDFB2 */, NULL) = -1 EBADF (%m)\n",
	       (long unsigned int) _IOC_NR(DRM_IOCTL_MODE_ADDFB2),
	       (long unsigned int) _IOC_SIZE(DRM_IOCTL_MODE_ADDFB2));

	ioctl(-1, _IOC(_IOC_READ, 0x45, 0x1, 0xff), lmagic);
	printf("ioctl(-1, %s, %#lx) = -1 EBADF (%m)\n",
	       "_IOC(_IOC_READ, 0x45, 0x1, 0xff)", lmagic);

	ioctl(-1, _IOC(_IOC_WRITE, 0x45, 0x1, 0xff), lmagic);
	printf("ioctl(-1, %s, %#lx) = -1 EBADF (%m)\n",
	       "_IOC(_IOC_WRITE, 0x45, 0x1, 0xff)", lmagic);

	ioctl(-1, _IOC(_IOC_READ|_IOC_WRITE, 0x45, 0xfe, 0xff), lmagic);
	printf("ioctl(-1, %s, %#lx) = -1 EBADF (%m)\n",
	       "_IOC(_IOC_READ|_IOC_WRITE, 0x45, 0xfe, 0xff)", lmagic);

	ioctl(-1, _IOC(_IOC_READ|_IOC_WRITE, 0x45, 0, 0), lmagic);
	printf("ioctl(-1, %s, %#lx) = -1 EBADF (%m)\n",
	       "_IOC(_IOC_READ|_IOC_WRITE, 0x45, 0, 0)", lmagic);

	puts("+++ exited with 0 +++");
	return 0;
}
#else

SKIP_MAIN_UNDEFINED("HAVE_DRM_H && HAVE_DRM_DRM_H");

#endif
