#!/bin/sh

# Ensure that strace -e trace=set works.

. "${srcdir=.}/init.sh"

check_prog ls
check_prog grep

$STRACE -e execve ls > /dev/null 2> $LOG &&
grep '^execve(' $LOG > /dev/null ||
	{ cat $LOG; fail_ 'strace -e execve does not work'; }

grep -v '^execve(' $LOG |
LC_ALL=C grep '^[[:alnum:]_]*(' > /dev/null &&
	{ cat $LOG; fail_ 'strace -e execve does not work properly'; }

$STRACE -e trace=process ls > /dev/null 2> $LOG &&
grep '^execve(' $LOG > /dev/null ||
	{ cat $LOG; fail_ 'strace -e trace=process does not work'; }

grep '^open' $LOG > /dev/null &&
	{ cat $LOG; fail_ 'strace -e trace=process does not work properly'; }

exit 0
