  ______________________________________________         ____
 /                                              \       /    \
 | strace has an extensive manual page          |      |-. .-.|
 | that covers all the possible options         \      (_@)(_@)
 | and contains several useful invocation        \     .---_  \
 | examples.                                     _\   /..   \_/
 |                                              /     |__.-^ /
 |                                              |         }  |
 \______________________________________________/        |   [
                                                         [  ]
