#!/bin/sh
#
# This script processes strace -ff -tt output.  It merges the contents of all
# STRACE_LOG.PID files and sorts them, printing result on the standard output.
#
# Copyright (c) 2012-2024 The strace developers.
#
# SPDX-License-Identifier: LGPL-2.1-or-later

show_usage()
{
	cat <<__EOF__
Usage: ${0##*/} STRACE_LOG

Finds all STRACE_LOG.PID files, adds PID prefix to every line,
then combines and sorts them, and prints result to standard output.

It is assumed that STRACE_LOGs were produced by strace with -tt[t]
option which prints timestamps (otherwise sorting won't do any good).
__EOF__
}

dd='\([0-9][0-9]\)'
ds='\([0-9][0-9]*\)'

if [ $# -ne 1 ]; then
	show_usage >&2
	exit 1
elif [ "$1" = '--help' ] || [ "$1" = '-h' ]; then
	show_usage
	exit 0
fi

logfile=$1

iterate_logfiles()
{
	local file suffix

	for file in "$logfile".*; do
		[ -f "$file" ] || continue
		suffix=${file#"$logfile".}
		[ "$suffix" -gt 0 ] 2> /dev/null ||
			continue
		"$@" "$suffix" "$file"
	done
}

max_suffix_length=0
process_suffix()
{
	local suffix len
	suffix="$1"; shift

	len=${#suffix}
	if [ $len -gt $max_suffix_length ]; then
		max_suffix_length=$len
	fi
}

process_logfile()
{
	local suffix file pid
	suffix="$1"; shift
	file="$1"; shift

	pid=$(printf "%-*s" $max_suffix_length $suffix)
	# Some strace logs have last line which is not '\n' terminated,
	# so add extra newline to every file.
	# Empty lines are removed later.
	sed -n "s/^\($dd:\)\?\($dd:\)\?\($ds\.\)\?$ds /\2\4\6\7 $pid \0/p" < "$file"
	echo
}

iterate_logfiles process_suffix

[ $max_suffix_length -gt 0 ] || {
	echo >&2 "${0##*/}: $logfile: strace output not found"
	exit 1
}

iterate_logfiles process_logfile |
	sort -s -n -k1,1 |
	sed -n 's/^[0-9][0-9]* //p' |
	grep -v '^$'

rc=$?
[ $rc -eq 1 ] &&
	echo >&2 "${0##*/}: $logfile.* files do not look like log files produced by 'strace -tt'"
exit $rc
