name: CI

on: [push, pull_request]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SLEEP_A_BIT: sleep 0.2
  VERBOSE: 1

jobs:
  whitespace-errors:
    name: Check for whitespace errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: check
        run: git diff-index --check --cached 4b825dc642cb6eb9a060e54bf8d69288fbee4904

  musl-gcc-x86_64:
    name: Build musl-gcc-x86_64
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    env:
      CC: gcc
      TARGET: x86_64
      STACKTRACE: libdw
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: install dependencies
        run: |
          apk add --no-cache \
            autoconf \
            automake \
            binutils-dev \
            bluez-dev \
            build-base \
            elfutils-dev \
            file \
            gawk \
            git \
            gzip \
            libfaketime \
            xz
      - name: build check
        run: |
          chmod +x ci/run-build-and-tests.sh
          ./ci/run-build-and-tests.sh
